enum ControllerConst{
    PartOne = 10000,

    PartOneBefore,
    PartOneBeforeLabel,
    PartOneBorder,
    PartOneHome,
    GuidePointer,
    PartOneOpen,
    PartOneFirst,
    PartOneMeeting,
    PartOneLabel,
    PartOneLongTap,
    PartOneRepeat,
    PartOneTeacher,
    PartOneNPC,
    PartOneEggshell,
    PartOneBloom,
    PartOneTalk,
    PartOneEnd,

    PartTwo = 20000,
    PartTwoHome,
    partTwoCross,
    PartTwoEnvelope,
    PartTwoLongTap,
    PartTwoLongTap1,
    PartTwoRepeat,
    PartTwoRepeat1,
    partTwoNPC,
    partTwoNPC1,
    partTwoTeacher,
    partTwoTeacher1,
    partTwoPhoneCall,
    partTwoTalk,
    PartTwoBloom,
    partTwoTalkTwo,
    PartTwoStar,
    PartTwoEndView,
    partTwoClock,
    partTwoCalling,
    PartTwoOpen,
    PartTwoRectLabel,
    PartTwoWeiyuSay,
    PartTwoWeiyuSelect,
    PartTwoWeiyuRepeat,
    PartTwoEggshell,

    
    PartThree = 30000,
    PartThreeClock,
    PartThreeHome,
    PartThreeOpen,
    PartThreeLabel,
    PartThreeTalk,
    PartThreeTalkMe,
    PartThreeLongTap,
    PartThreeRepeat,
    partThreeTeacher,
    partThreeNPC,
    PartThreePerson,
    PartThreeEnd,

    Common = 40000,
    TopBar,
    TopBarPopup1,
    TopBarPopup2,

    Loading = 50000,
}